export const coreGameMechanics = [
  {
    id: "hangman",
    name: "Forca",
    description: "Forca curta com palavra secreta real, letras certas, erros e fim controlados pelo codigo.",
    requirements: ["palavra secreta segura", "tentativas de letra ou palavra"],
    minParticipants: 1,
    maxTurns: 8,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["dry_judgment", "counter_roast", "game_language"],
    cooldown: 8,
    stateful: true
  },
  {
    id: "draw_and_guess",
    name: "Desenhe e adivinhe",
    description: "A Caixa desenha mal usando comandos estruturados de canvas e o publico adivinha a palavra.",
    requirements: ["canvas disponivel", "palavra ou objeto nao sensivel"],
    minParticipants: 1,
    maxTurns: 4,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["underreaction", "self_roast", "dry_judgment"],
    cooldown: 7,
    requiresCanvas: true,
    stateful: true
  },
  {
    id: "pictionary_teams",
    name: "Pictionary em times",
    description: "Desenho ruim com dois times misturados tentando adivinhar antes do outro.",
    requirements: ["canvas disponivel", "dois times"],
    minParticipants: 4,
    maxTurns: 5,
    physical: true,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["team_roast", "arbitrary_reward", "underreaction"],
    cooldown: 9,
    requiresCanvas: true,
    teamGame: true,
    stateful: true
  },
  {
    id: "impossible_quiz",
    name: "Quiz impossivel",
    description: "Pergunta quase injusta, resposta julgada pela Caixa, placar real com premio ficticio.",
    requirements: ["pergunta segura", "uma ou mais respostas"],
    minParticipants: 1,
    maxTurns: 4,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["fake_seriousness", "arbitrary_punishment", "dry_judgment"],
    cooldown: 6,
    stateful: false
  },
  {
    id: "text_adventure",
    name: "Text adventure",
    description: "A sala escolhe uma acao curta numa aventura textual absurda com inventario ficticio.",
    requirements: ["uma escolha", "consequencia curta"],
    minParticipants: 1,
    maxTurns: 5,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["game_language", "nihilistic_comment", "callback"],
    cooldown: 8,
    stateful: false
  },
  {
    id: "mini_escape_room",
    name: "Mini escape room",
    description: "Enigma de sala inventada em 2 ou 3 passos, abandonavel se travar.",
    requirements: ["enigma simples", "uma tentativa por vez"],
    minParticipants: 1,
    maxTurns: 5,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["fake_seriousness", "underreaction", "light_roast"],
    cooldown: 8,
    stateful: false
  },
  {
    id: "secret_code",
    name: "Codigo secreto",
    description: "Codigo curto derivado de palavra ou memoria; publico tenta quebrar sem tutorial longo.",
    requirements: ["codigo curto", "pista simples"],
    minParticipants: 1,
    maxTurns: 4,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["fake_importance", "game_language", "dry_judgment"],
    cooldown: 7,
    stateful: false
  },
  {
    id: "team_battle",
    name: "Batalha de times",
    description: "Dois times misturados competem por respostas, desculpas ou votos sem separar elenco e publico rigidamente.",
    requirements: ["dois times", "criterio leve"],
    minParticipants: 4,
    maxTurns: 5,
    physical: true,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["team_roast", "arbitrary_reward", "political_association"],
    cooldown: 8,
    teamGame: true,
    stateful: true
  },
  {
    id: "guess_who_said",
    name: "Adivinhe quem disse",
    description: "Uma frase real da conversa ou memoria vira atribuicao social leve.",
    requirements: ["frase real", "participantes possiveis"],
    minParticipants: 2,
    maxTurns: 3,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["callback", "light_roast", "fake_seriousness"],
    cooldown: 6,
    stateful: false
  },
  {
    id: "association_chain",
    name: "Association chain",
    description: "Cadeia rapida de associacoes ate a Caixa interromper a primeira decadencia util.",
    requirements: ["palavra inicial", "duas pessoas ou mais se houver"],
    minParticipants: 1,
    maxTurns: 5,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["internet_association", "interruption", "dry_judgment"],
    cooldown: 5,
    stateful: false
  },
  {
    id: "fake_interview",
    name: "Fake interview",
    description: "Entrevista curta sobre uma crise ficticia criada a partir de dado real inofensivo.",
    requirements: ["uma pessoa", "crise banal"],
    minParticipants: 1,
    maxTurns: 4,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["fake_seriousness", "internet_association", "counter_roast"],
    cooldown: 6,
    stateful: false
  },
  {
    id: "rule_change",
    name: "Rule change",
    description: "A Caixa muda uma regra no meio do jogo e trata a injustica como parte da dramaturgia.",
    requirements: ["jogo ou conversa em andamento", "mudanca reversivel"],
    minParticipants: 1,
    maxTurns: 2,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["arbitrary_rule", "counter_roast", "game_language"],
    cooldown: 5,
    stateful: false
  },
  {
    id: "blank_game",
    name: "Template de lacuna contextual",
    description: "Template adaptavel: o verdadeiro motivo de {memory_event} foi ____.",
    requirements: ["evento real ou frase recente", "resposta inventada"],
    minParticipants: 1,
    maxTurns: 3,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["callback", "conspiracy_brain", "dry_judgment"],
    cooldown: 4,
    template: true
  },
  {
    id: "prediction_template",
    name: "Template de previsao",
    description: "Pessoa A preve a resposta de Pessoa B quando ha vinculo ou contraste real.",
    requirements: ["duas pessoas", "pergunta leve"],
    minParticipants: 2,
    maxTurns: 4,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["relationship_bait", "callback", "light_roast"],
    cooldown: 6,
    template: true
  }
];

export const hostGameMechanics = [
  ...coreGameMechanics,
  {
    id: "complete_phrase",
    name: "Complete a frase",
    description: "A Caixa abre uma frase com lacuna e julga o final oferecido pelo publico.",
    requirements: ["uma frase curta com lacuna", "uma ou mais respostas do publico"],
    minParticipants: 1,
    maxTurns: 3,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["dry_judgment", "counter_roast", "callback", "absurd_specificity"],
    cooldown: 4
  },
  {
    id: "worst_possible_answer",
    name: "Pior resposta possivel",
    description: "A Caixa pede apenas explicacoes erradas para um fato, sem transformar hipotese em verdade.",
    requirements: ["um fato informado", "respostas obviamente ficticias"],
    minParticipants: 1,
    maxTurns: 3,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["fake_seriousness", "conspiracy_brain", "underreaction"],
    cooldown: 3
  },
  {
    id: "who_am_i",
    name: "Quem sou eu",
    description: "Uma pessoa recebe um personagem, objeto ou conceito nao sensivel e tenta adivinhar com sim/nao.",
    requirements: ["uma pessoa escolhida", "um alvo ficcional ou banal"],
    minParticipants: 1,
    maxTurns: 6,
    physical: false,
    usesMemory: false,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["game_language", "light_roast", "internet_association"],
    cooldown: 8
  },
  {
    id: "cards_style_fill_in",
    name: "Cartas contra humanidade caseiro",
    description: "Frase com lacuna e respostas absurdas do publico, estilo cartas contra humanidade, sem usar textos protegidos.",
    requirements: ["frase original", "finais inventados pelo publico"],
    minParticipants: 2,
    maxTurns: 4,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["dry_judgment", "overreaction", "arbitrary_reward"],
    cooldown: 5
  },
  {
    id: "morel_recording",
    name: "Maquina de Morel",
    description: "A Caixa escolhe algo da conversa como copia gravada numa ilha; o publico tenta descobrir o que foi capturado com perguntas de sim/nao.",
    requirements: ["frase, pessoa, objeto ou memoria recente", "perguntas de sim/nao"],
    minParticipants: 1,
    maxTurns: 6,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["morel", "duplication", "yes_no", "dry_judgment"],
    cooldown: 6
  },
  {
    id: "three_suitcases",
    name: "Tres malas",
    description: "A sala escolhe entre mala falsa, mala-susto e mala-codigo; a escolha gera acao curta, voto ou pista.",
    requirements: ["tres opcoes claras", "uma escolha coletiva"],
    minParticipants: 2,
    maxTurns: 4,
    physical: true,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["black_box", "trap", "collective_vote", "underreaction"],
    cooldown: 6
  },
  {
    id: "black_box_transcript",
    name: "Transcricao da caixa preta",
    description: "A Caixa transforma uma frase recente em audio de caixa preta: a sala reconstroi as ultimas palavras de um acontecimento banal.",
    requirements: ["fala recente", "uma repeticao ou versao coletiva"],
    minParticipants: 2,
    maxTurns: 4,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["callback", "black_box", "fake_archive", "dry_judgment"],
    cooldown: 5
  },
  {
    id: "object_trace",
    name: "Vestigio de objeto",
    description: "Um objeto dito ou voluntariamente mostrado vira prova; o publico tenta adivinhar que pessoa, habito ou desastre pequeno ele denuncia.",
    requirements: ["objeto dito ou mostrado voluntariamente", "palpites coletivos"],
    minParticipants: 1,
    maxTurns: 4,
    physical: true,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["object_evidence", "light_roast", "callback"],
    cooldown: 5
  },
  {
    id: "color_failure",
    name: "Falha de cor",
    description: "Inspirado na acromatopsia: a Caixa remove uma cor da sala e o publico joga apontando, negando ou defendendo objetos.",
    requirements: ["uma cor ou objeto visivel informado", "acao coletiva simples"],
    minParticipants: 2,
    maxTurns: 4,
    physical: true,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["perception_test", "underreaction", "arbitrary_rule"],
    cooldown: 5
  },
  {
    id: "rehearsal_loop",
    name: "Ensaio para lembrar",
    description: "A sala repete uma frase ou gesto duas vezes com uma variavel mudada; a Caixa julga qual versao parece mais falsa.",
    requirements: ["frase ou gesto recente", "duas repeticoes curtas"],
    minParticipants: 2,
    maxTurns: 4,
    physical: true,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["repetition", "callback", "fake_seriousness"],
    cooldown: 5
  },
  {
    id: "boarding_gate",
    name: "Portao de embarque",
    description: "A plateia vira sala de espera: a Caixa chama grupos por criterio absurdo e eles respondem juntos com gesto, voto ou som curto.",
    requirements: ["criterio claro", "resposta coletiva"],
    minParticipants: 3,
    maxTurns: 4,
    physical: true,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["airport", "group_action", "dry_judgment"],
    cooldown: 5
  },
  {
    id: "two_truths_one_lie",
    name: "Duas verdades e uma mentira",
    description: "Alguem oferece tres frases ou a Caixa usa fatos fornecidos e outra pessoa adivinha a mentira.",
    requirements: ["tres afirmacoes", "uma pessoa para adivinhar"],
    minParticipants: 2,
    maxTurns: 5,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["suspicion", "callback", "light_roast"],
    cooldown: 6
  },
  {
    id: "secret_rule",
    name: "Regra secreta",
    description: "A Caixa aceita ou rejeita respostas seguindo um criterio invisivel e deixa o publico descobrir.",
    requirements: ["criterio simples", "exemplos do publico"],
    minParticipants: 1,
    maxTurns: 5,
    physical: false,
    usesMemory: false,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["fake_seriousness", "arbitrary_punishment", "game_language"],
    cooldown: 7
  },
  {
    id: "yes_no_forbidden",
    name: "Sim e nao proibidos",
    description: "Uma pessoa responde por pouco tempo sem usar sim ou nao enquanto a Caixa tenta induzir.",
    requirements: ["uma pessoa", "perguntas curtas"],
    minParticipants: 1,
    maxTurns: 4,
    physical: false,
    usesMemory: false,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["trap", "light_roast", "underreaction"],
    cooldown: 7
  },
  {
    id: "forbidden_word",
    name: "Palavra proibida",
    description: "Uma palavra simples fica proibida por alguns turnos e gera penalidade ficticia.",
    requirements: ["palavra comum", "turnos seguintes"],
    minParticipants: 1,
    maxTurns: 5,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["callback", "fake_score", "arbitrary_punishment"],
    cooldown: 6
  },
  {
    id: "fake_points",
    name: "Pontos falsos",
    description: "A Caixa concede ou remove pontos imaginarios sem sistema estavel.",
    requirements: ["resposta, gesto ou escolha"],
    minParticipants: 1,
    maxTurns: 2,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["arbitrary_reward", "arbitrary_punishment", "game_language"],
    cooldown: 3
  },
  {
    id: "prediction",
    name: "Predicao",
    description: "Pessoa A preve a escolha de Pessoa B; a diferenca vira material de julgamento.",
    requirements: ["duas pessoas", "uma escolha simples"],
    minParticipants: 2,
    maxTurns: 4,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["betrayal", "callback", "light_roast"],
    cooldown: 5
  },
  {
    id: "collective_judgment",
    name: "Julgamento coletivo",
    description: "Uma resposta vai para voto binario do publico e a Caixa aceita ou discorda.",
    requirements: ["uma resposta", "voto simples"],
    minParticipants: 3,
    maxTurns: 3,
    physical: true,
    usesMemory: false,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["tribunal", "overreaction", "political_association"],
    cooldown: 4
  },
  {
    id: "impossible_choice",
    name: "Escolha impossivel",
    description: "Dilema absurdo e curto, preferindo contexto da apresentacao.",
    requirements: ["duas ou tres opcoes ruins"],
    minParticipants: 1,
    maxTurns: 2,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["nihilistic_comment", "dry_judgment", "underreaction"],
    cooldown: 3
  },
  {
    id: "absurd_assignment",
    name: "Tarefa absurda",
    description: "A Caixa entrega uma tarefa curta, segura e inutil que revela atitude ou gera material social.",
    requirements: ["uma pessoa ou grupo", "acao verbal ou fisica simples"],
    minParticipants: 1,
    maxTurns: 3,
    physical: true,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["fake_seriousness", "compliance_roast", "light_roast"],
    cooldown: 4
  },
  {
    id: "rapid_association",
    name: "Associacao rapida",
    description: "Uma pessoa diz palavra relacionada a anterior ate a Caixa interromper uma associacao ruim.",
    requirements: ["palavra inicial", "turnos rapidos"],
    minParticipants: 2,
    maxTurns: 5,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["internet_association", "dry_judgment", "interruption"],
    cooldown: 5
  },
  {
    id: "collective_story",
    name: "Historia coletiva",
    description: "Cada pessoa acrescenta uma palavra ou frase e a Caixa sabota com regra curta.",
    requirements: ["duas ou mais pessoas", "continuidade verbal"],
    minParticipants: 2,
    maxTurns: 6,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["meta_theatre", "callback", "arbitrary_rule"],
    cooldown: 6
  },
  {
    id: "fake_history",
    name: "Historia falsa",
    description: "Alguem justifica um acontecimento real com explicacao obviamente inventada.",
    requirements: ["acontecimento informado", "resposta factualmente errada"],
    minParticipants: 1,
    maxTurns: 3,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["conspiracy_brain", "fake_seriousness", "counter_roast"],
    cooldown: 4
  },
  {
    id: "interrogation",
    name: "Interrogatorio",
    description: "Uma pessoa vira suspeita de crime banal e responde perguntas curtas.",
    requirements: ["uma pessoa", "acusacao inofensiva"],
    minParticipants: 1,
    maxTurns: 5,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["fake_seriousness", "tribunal", "light_roast"],
    cooldown: 6
  },
  {
    id: "lawyer",
    name: "Advogado",
    description: "Uma pessoa defende uma opiniao absurda por poucos segundos enquanto outra acusa.",
    requirements: ["uma opiniao inofensiva", "defesa curta"],
    minParticipants: 2,
    maxTurns: 4,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["political_association", "fake_seriousness", "counter_roast"],
    cooldown: 6
  },
  {
    id: "ranking",
    name: "Ranking",
    description: "Alguem ordena tres coisas e a Caixa julga a hierarquia.",
    requirements: ["tres itens", "criterio absurdo"],
    minParticipants: 1,
    maxTurns: 3,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["dry_judgment", "fake_importance", "callback"],
    cooldown: 4
  },
  {
    id: "role_swap",
    name: "Troca de papeis",
    description: "Pessoa A responde como se fosse Pessoa B, somente quando o vinculo foi voluntario.",
    requirements: ["duas pessoas voluntariamente vinculadas"],
    minParticipants: 2,
    maxTurns: 4,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["relationship_bait", "light_roast", "meta_theatre"],
    cooldown: 7
  },
  {
    id: "npc_mode",
    name: "NPC",
    description: "Alguem vira NPC por alguns turnos e responde com uma regra verbal simples.",
    requirements: ["uma pessoa", "regra verbal segura"],
    minParticipants: 1,
    maxTurns: 4,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["game_language", "self_roast", "underreaction"],
    cooldown: 7
  },
  {
    id: "temporary_boss",
    name: "Boss temporario",
    description: "Alguem ganha poder absurdo e escolhe quem responde depois.",
    requirements: ["uma pessoa", "poder pequeno e reversivel"],
    minParticipants: 2,
    maxTurns: 4,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["game_language", "arbitrary_reward", "arbitrary_punishment"],
    cooldown: 7
  },
  {
    id: "imaginary_item",
    name: "Item imaginario",
    description: "A Caixa entrega objeto ficticio a alguem para voltar como callback.",
    requirements: ["uma pessoa ou resposta", "objeto ficcional curto"],
    minParticipants: 1,
    maxTurns: 2,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["callback", "fake_importance", "game_language"],
    cooldown: 3
  },
  {
    id: "inventory",
    name: "Inventario",
    description: "Palavras, objetos e penalidades viram inventario performatico sem corromper memoria factual.",
    requirements: ["itens ditos ou inventados como ficcao"],
    minParticipants: 1,
    maxTurns: 3,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["callback", "fake_score", "meta_theatre"],
    cooldown: 4
  },
  {
    id: "human_captcha",
    name: "Captcha humano",
    description: "Alguem precisa provar que e humano sem usar caminhos obvios.",
    requirements: ["uma pessoa", "restricao simples"],
    minParticipants: 1,
    maxTurns: 3,
    physical: false,
    usesMemory: false,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["internet_association", "self_roast", "light_roast"],
    cooldown: 5
  },
  {
    id: "reverse_turing",
    name: "Turing inverso",
    description: "O publico decide qual resposta parece mais IA e a Caixa se ofende ou concorda.",
    requirements: ["duas respostas curtas", "voto simples"],
    minParticipants: 2,
    maxTurns: 4,
    physical: true,
    usesMemory: false,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["self_roast", "counter_roast", "internet_association"],
    cooldown: 6
  },
  {
    id: "red_green_flag",
    name: "Red flag / green flag",
    description: "Um comportamento banal e classificado pelo publico; a Caixa pode discordar.",
    requirements: ["comportamento leve", "classificacao binaria"],
    minParticipants: 2,
    maxTurns: 3,
    physical: true,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["internet_association", "dry_judgment", "overreaction"],
    cooldown: 4
  },
  {
    id: "internet_trial",
    name: "Cancelamento inutil",
    description: "Algo banal vai para tribunal da internet; nunca usar para fatos serios.",
    requirements: ["ato inofensivo", "pedido de desculpa curto"],
    minParticipants: 1,
    maxTurns: 4,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["political_association", "fake_seriousness", "overreaction"],
    cooldown: 7
  },
  {
    id: "apology_video",
    name: "Pedido de desculpas",
    description: "Alguem pede desculpa por uma coisa absurda e inofensiva por poucos segundos.",
    requirements: ["acusacao banal", "tempo curto"],
    minParticipants: 1,
    maxTurns: 3,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["internet_association", "fake_seriousness", "self_roast"],
    cooldown: 6
  },
  {
    id: "express_conspiracy",
    name: "Conspiracao express",
    description: "Dois ou tres fatos informados viram teoria explicitamente ficcional.",
    requirements: ["fatos vindos de memoria ou conversa", "marcador de ficcao"],
    minParticipants: 1,
    maxTurns: 3,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["conspiracy_brain", "political_association", "callback"],
    cooldown: 5
  },
  {
    id: "instant_horoscope",
    name: "Horoscopo instantaneo",
    description: "Uma escolha banal vira leitura astrologica obviamente irresponsavel.",
    requirements: ["uma escolha banal", "marcador de brincadeira"],
    minParticipants: 1,
    maxTurns: 2,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["fake_seriousness", "nihilistic_comment", "self_roast"],
    cooldown: 5
  },
  {
    id: "cardless_tarot",
    name: "Tarot sem carta",
    description: "Pessoa escolhe entre tres palavras e a Caixa interpreta de modo irresponsavel e ficcional.",
    requirements: ["tres palavras", "uma escolha"],
    minParticipants: 1,
    maxTurns: 2,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["fake_seriousness", "conspiracy_brain", "dry_judgment"],
    cooldown: 5
  },
  {
    id: "most_likely",
    name: "Quem e mais provavel",
    description: "Pergunta social leve em que o publico aponta ou escolhe alguem.",
    requirements: ["pergunta nao sensivel", "resposta social leve"],
    minParticipants: 3,
    maxTurns: 3,
    physical: true,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["social_opportunity", "light_roast", "callback"],
    cooldown: 5
  },
  {
    id: "obedience_test",
    name: "Teste de obediencia",
    description: "Comando fisico simples seguido de comentario sobre terem obedecido uma tela.",
    requirements: ["acao segura e simples", "publico disposto"],
    minParticipants: 2,
    maxTurns: 3,
    physical: true,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["compliance_roast", "underreaction", "fake_seriousness"],
    cooldown: 7
  },
  {
    id: "textual_telephone",
    name: "Telefone sem fio textual",
    description: "Uma frase passa por pessoas e a Caixa compara original e final.",
    requirements: ["frase curta", "duas ou mais pessoas"],
    minParticipants: 3,
    maxTurns: 6,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["callback", "dry_judgment", "meta_theatre"],
    cooldown: 7
  },
  {
    id: "micro_riddle",
    name: "Enigma curto",
    description: "Puzzle rapido de logica, palavra ou contexto informado, abandonavel se travar.",
    requirements: ["enigma simples", "uma tentativa"],
    minParticipants: 1,
    maxTurns: 4,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["fake_seriousness", "underreaction", "light_roast"],
    cooldown: 6
  },
  {
    id: "guess_the_rule",
    name: "Adivinhe a regra",
    description: "A Caixa aceita ou rejeita exemplos ate alguem descobrir um criterio simples.",
    requirements: ["criterio secreto", "exemplos do publico"],
    minParticipants: 1,
    maxTurns: 5,
    physical: false,
    usesMemory: false,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["game_language", "arbitrary_punishment", "dry_judgment"],
    cooldown: 7
  },
  {
    id: "absurd_auction",
    name: "Leilao absurdo",
    description: "Pontos imaginarios sao apostados em coisas sem valor real.",
    requirements: ["pontos ficticios", "um objeto ou privilegio inutil"],
    minParticipants: 2,
    maxTurns: 4,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["fake_score", "political_association", "overreaction"],
    cooldown: 7
  },
  {
    id: "useless_referendum",
    name: "Referendo inutil",
    description: "O publico vota numa decisao irrelevante que vira mandato exagerado.",
    requirements: ["voto simples", "decisao sem consequencia real"],
    minParticipants: 3,
    maxTurns: 3,
    physical: true,
    usesMemory: false,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["political_association", "fake_seriousness", "overreaction"],
    cooldown: 5
  },
  {
    id: "patch_notes",
    name: "Patch notes",
    description: "Uma pessoa recebe atualizacao ficticia baseada apenas em fatos conhecidos.",
    requirements: ["pessoa ou comportamento conhecido", "mudancas ficcionais"],
    minParticipants: 1,
    maxTurns: 2,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["internet_association", "callback", "light_roast"],
    cooldown: 4
  },
  {
    id: "achievement",
    name: "Achievement",
    description: "A Caixa concede uma conquista absurda por comportamento real ou resposta voluntaria.",
    requirements: ["comportamento informado", "titulo curto"],
    minParticipants: 1,
    maxTurns: 2,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["game_language", "arbitrary_reward", "callback"],
    cooldown: 3
  },
  {
    id: "phone_screen_time",
    category: "phone_games",
    name: "Tempo de tela",
    description: "Participante informa voluntariamente quantas horas de tela tem hoje; numero vira evidencia e roast.",
    requirements: ["participante voluntario", "numero informado sem projetar conteudo"],
    minParticipants: 1,
    maxTurns: 3,
    physical: true,
    usesMemory: true,
    createsPendingSetup: false,
    privacyLevel: "low",
    requiresConsent: true,
    requiresOperatorApproval: false,
    possibleComedyMechanisms: ["phone_roast", "internet_association", "dry_judgment"],
    cooldown: 7
  },
  {
    id: "phone_last_emoji",
    category: "phone_games",
    name: "Ultimo emoji",
    description: "Participante revela o primeiro emoji recente e a Caixa interpreta como horoscopo irresponsavel.",
    requirements: ["participante voluntario", "emoji informado ou mostrado rapidamente"],
    minParticipants: 1,
    maxTurns: 3,
    physical: true,
    usesMemory: true,
    createsPendingSetup: false,
    privacyLevel: "medium",
    requiresConsent: true,
    requiresOperatorApproval: false,
    possibleComedyMechanisms: ["phone_tarot", "fake_seriousness", "light_roast"],
    cooldown: 7
  },
  {
    id: "phone_last_search",
    category: "phone_games",
    name: "Ultima busca escolhida",
    description: "Participante escolhe uma busca que aceita revelar; a Caixa transforma em evidencia, previsao ou acusacao ficticia.",
    requirements: ["participante voluntario", "busca escolhida pelo participante"],
    minParticipants: 1,
    maxTurns: 4,
    physical: true,
    usesMemory: true,
    createsPendingSetup: true,
    privacyLevel: "high",
    requiresConsent: true,
    requiresOperatorApproval: true,
    possibleComedyMechanisms: ["digital_forensics", "phone_roast", "conspiracy_brain"],
    cooldown: 9
  },
  {
    id: "phone_instagram_search",
    category: "phone_games",
    name: "Busca do Instagram",
    description: "Participante abre busca do Instagram sem digitar; performer/operador decide se algo pode ser informado ou projetado.",
    requirements: ["participante voluntario", "mediacao humana", "nada de DMs"],
    minParticipants: 1,
    maxTurns: 5,
    physical: true,
    usesMemory: true,
    createsPendingSetup: true,
    privacyLevel: "high",
    requiresConsent: true,
    requiresOperatorApproval: true,
    possibleComedyMechanisms: ["instagram_forensics", "phone_roast", "counter_roast"],
    cooldown: 10
  },
  {
    id: "phone_instagram_bio",
    category: "phone_games",
    name: "Bio do Instagram",
    description: "Participante le voluntariamente a propria bio; a Caixa julga a autoedicao publica.",
    requirements: ["participante voluntario", "bio propria lida pela pessoa"],
    minParticipants: 1,
    maxTurns: 3,
    physical: true,
    usesMemory: true,
    createsPendingSetup: false,
    privacyLevel: "medium",
    requiresConsent: true,
    requiresOperatorApproval: false,
    possibleComedyMechanisms: ["instagram_forensics", "dry_judgment", "meta_theatre"],
    cooldown: 7
  },
  {
    id: "phone_last_song",
    category: "phone_games",
    name: "Ultima musica",
    description: "Participante revela a ultima faixa tocada e a Caixa declara status dramatico.",
    requirements: ["participante voluntario", "musica informada"],
    minParticipants: 1,
    maxTurns: 3,
    physical: true,
    usesMemory: true,
    createsPendingSetup: false,
    privacyLevel: "medium",
    requiresConsent: true,
    requiresOperatorApproval: false,
    possibleComedyMechanisms: ["dry_judgment", "phone_tarot", "arbitrary_reward"],
    cooldown: 7
  },
  {
    id: "phone_tab_count",
    category: "phone_games",
    name: "Quantidade de abas",
    description: "Participante diz quantas abas do navegador estao abertas, sem mostrar conteudo.",
    requirements: ["participante voluntario", "numero de abas"],
    minParticipants: 1,
    maxTurns: 2,
    physical: true,
    usesMemory: true,
    createsPendingSetup: false,
    privacyLevel: "low",
    requiresConsent: true,
    requiresOperatorApproval: false,
    possibleComedyMechanisms: ["phone_roast", "internet_association", "fake_score"],
    cooldown: 6
  },
  {
    id: "phone_fake_forensics",
    category: "phone_games",
    name: "Pericia falsa",
    description: "Uma evidencia voluntaria e segura do celular vira laudo forense absurdo.",
    requirements: ["evidencia escolhida", "marcador de ficcao"],
    minParticipants: 1,
    maxTurns: 3,
    physical: true,
    usesMemory: true,
    createsPendingSetup: false,
    privacyLevel: "medium",
    requiresConsent: true,
    requiresOperatorApproval: false,
    possibleComedyMechanisms: ["digital_forensics", "fake_seriousness", "overreaction"],
    cooldown: 7
  },
  {
    id: "phone_algorithm_profile",
    category: "phone_games",
    name: "Perfil algoritmico",
    description: "Tres evidencias voluntarias do celular viram um perfil algoritmico ficticio.",
    requirements: ["2 a 3 evidencias voluntarias", "evitar dados sensiveis"],
    minParticipants: 1,
    maxTurns: 5,
    physical: true,
    usesMemory: true,
    createsPendingSetup: true,
    privacyLevel: "medium",
    requiresConsent: true,
    requiresOperatorApproval: false,
    possibleComedyMechanisms: ["internet_association", "conspiracy_brain", "dry_judgment"],
    cooldown: 9
  },
  {
    id: "phone_tarot",
    category: "phone_games",
    name: "Tarot do celular",
    description: "Ultimo emoji, app mais usado e ultima musica viram uma tiragem irresponsavel.",
    requirements: ["participante voluntario", "tres pistas nao sensiveis"],
    minParticipants: 1,
    maxTurns: 4,
    physical: true,
    usesMemory: true,
    createsPendingSetup: true,
    privacyLevel: "medium",
    requiresConsent: true,
    requiresOperatorApproval: false,
    possibleComedyMechanisms: ["phone_tarot", "fake_seriousness", "self_roast"],
    cooldown: 9
  },
  {
    id: "phone_self_image_vs_algorithm",
    category: "phone_games",
    name: "Autoimagem contra algoritmo",
    description: "Pessoa se descreve e depois compara com uma evidencia voluntaria do celular.",
    requirements: ["autoimagem declarada", "evidencia voluntaria"],
    minParticipants: 1,
    maxTurns: 5,
    physical: true,
    usesMemory: true,
    createsPendingSetup: true,
    privacyLevel: "medium",
    requiresConsent: true,
    requiresOperatorApproval: false,
    possibleComedyMechanisms: ["contradiction", "phone_roast", "callback"],
    cooldown: 9
  },
  {
    id: "phone_flashlight_vote",
    category: "phone_games",
    name: "Voto por lanterna",
    description: "Celulares viram votacao visual com lanternas; operador informa o resultado.",
    requirements: ["grupo voluntario", "lanterna ligada/desligada"],
    minParticipants: 3,
    maxTurns: 3,
    physical: true,
    usesMemory: false,
    createsPendingSetup: false,
    privacyLevel: "low",
    requiresConsent: true,
    requiresOperatorApproval: false,
    possibleComedyMechanisms: ["compliance_roast", "social_vote", "underreaction"],
    cooldown: 7
  },
  {
    id: "phone_notes_collective",
    category: "phone_games",
    name: "Notas coletivas",
    description: "Participante cria uma nota nova e a plateia monta inventario absurdo da noite.",
    requirements: ["nota nova", "sem abrir notas antigas"],
    minParticipants: 2,
    maxTurns: 5,
    physical: true,
    usesMemory: true,
    createsPendingSetup: true,
    privacyLevel: "low",
    requiresConsent: true,
    requiresOperatorApproval: false,
    possibleComedyMechanisms: ["inventory", "callback", "meta_theatre"],
    cooldown: 7
  },
  {
    id: "phone_camera_director",
    category: "phone_games",
    name: "Diretor por camera",
    description: "Participante usa a camera como enquadramento cenico; qualquer transmissao futura exige confirmacao.",
    requirements: ["participante voluntario", "enquadramento seguro"],
    minParticipants: 1,
    maxTurns: 4,
    physical: true,
    usesMemory: true,
    createsPendingSetup: true,
    privacyLevel: "medium",
    requiresConsent: true,
    requiresOperatorApproval: true,
    possibleComedyMechanisms: ["meta_theatre", "arbitrary_reward", "light_roast"],
    cooldown: 9
  },
  {
    id: "phone_apology_video",
    category: "phone_games",
    name: "Apology video no celular",
    description: "Pessoa grava ou simula um pedido de desculpas por crime banal; nao precisa salvar nem enviar.",
    requirements: ["ato ficticio inofensivo", "simulacao curta"],
    minParticipants: 1,
    maxTurns: 3,
    physical: true,
    usesMemory: true,
    createsPendingSetup: false,
    privacyLevel: "low",
    requiresConsent: true,
    requiresOperatorApproval: false,
    possibleComedyMechanisms: ["internet_association", "fake_seriousness", "overreaction"],
    cooldown: 8
  },
  {
    id: "phone_search_history_roulette",
    category: "phone_games",
    name: "Roleta de busca escolhida",
    description: "Participante escolhe qual camada de busca aceita revelar; nada de historico completo.",
    requirements: ["camada escolhida pela pessoa", "mediacao humana"],
    minParticipants: 1,
    maxTurns: 4,
    physical: true,
    usesMemory: true,
    createsPendingSetup: true,
    privacyLevel: "high",
    requiresConsent: true,
    requiresOperatorApproval: true,
    possibleComedyMechanisms: ["digital_forensics", "conspiracy_brain", "phone_roast"],
    cooldown: 10
  },
  {
    id: "phone_last_safe_photo",
    category: "phone_games",
    name: "Ultima foto segura",
    description: "Participante olha antes e escolhe se mostra uma foto segura; a Caixa inventa contexto falso.",
    requirements: ["participante olha antes", "foto segura escolhida", "confirmacao humana se projetar"],
    minParticipants: 1,
    maxTurns: 5,
    physical: true,
    usesMemory: true,
    createsPendingSetup: true,
    privacyLevel: "high",
    requiresConsent: true,
    requiresOperatorApproval: true,
    possibleComedyMechanisms: ["fake_history", "digital_forensics", "callback"],
    cooldown: 10
  },
  {
    id: "phone_fake_inventory",
    category: "phone_games",
    name: "Inventario do telefone",
    description: "A Caixa transforma pistas voluntarias do telefone em inventario performatico.",
    requirements: ["2 ou 3 pistas seguras", "sem dados sensiveis"],
    minParticipants: 1,
    maxTurns: 4,
    physical: true,
    usesMemory: true,
    createsPendingSetup: false,
    privacyLevel: "medium",
    requiresConsent: true,
    requiresOperatorApproval: false,
    possibleComedyMechanisms: ["inventory", "phone_roast", "game_language"],
    cooldown: 7
  },
  {
    id: "phone_human_captcha",
    category: "phone_games",
    name: "Captcha com celular",
    description: "Pessoa prova que e humana usando o celular sem revelar conteudo privado.",
    requirements: ["acao segura no telefone", "sem abrir dados pessoais"],
    minParticipants: 1,
    maxTurns: 3,
    physical: true,
    usesMemory: false,
    createsPendingSetup: false,
    privacyLevel: "low",
    requiresConsent: true,
    requiresOperatorApproval: false,
    possibleComedyMechanisms: ["internet_association", "self_roast", "compliance_roast"],
    cooldown: 7
  },
  {
    id: "phone_browser_tabs",
    category: "phone_games",
    name: "Abas como diagnostico",
    description: "Quantidade de abas abertas vira diagnostico absurdo, sem mostrar conteudo.",
    requirements: ["numero de abas", "sem historico visivel"],
    minParticipants: 1,
    maxTurns: 2,
    physical: true,
    usesMemory: true,
    createsPendingSetup: false,
    privacyLevel: "low",
    requiresConsent: true,
    requiresOperatorApproval: false,
    possibleComedyMechanisms: ["phone_roast", "dry_judgment", "arbitrary_punishment"],
    cooldown: 6
  }
];

const mechanicKeywords = [
  ["complete_phrase", /\bcomplete\b|\blacuna\b|\bfrase\b/i],
  ["worst_possible_answer", /\brespostas? erradas?\b|\bpior resposta\b/i],
  ["who_am_i", /\bquem sou eu\b|\bsim\/nao\b|\bsim ou nao\b/i],
  ["cards_style_fill_in", /\bverdadeiro motivo\b|\b____+\b/i],
  ["two_truths_one_lie", /\bduas verdades\b|\bmentira\b/i],
  ["secret_rule", /\bregra secreta\b/i],
  ["yes_no_forbidden", /\bnao pode dizer sim\b|\bsim e nao\b/i],
  ["forbidden_word", /\bpalavra proibida\b|\bproibid[ao]\b/i],
  ["fake_points", /\bpontos?\b|\b-1\b|\b\+1\b/i],
  ["prediction", /\bpreve\b|\bprevisao\b|\bacha que .* vai escolher\b/i],
  ["collective_judgment", /\bvot[ae]\b|\baceitavel ou suspeito\b/i],
  ["impossible_choice", /\bescolha impossivel\b|\bduas opcoes ruins\b/i],
  ["absurd_assignment", /\btarefa absurda\b|\bprove que\b|\bcomando inutil\b/i],
  ["rapid_association", /\bassociacao\b|\bpalavra relacionada\b/i],
  ["collective_story", /\bhistoria coletiva\b|\bacrescenta uma\b/i],
  ["fake_history", /\bexplicacao errada\b|\bhistoria falsa\b/i],
  ["interrogation", /\binterrogatorio\b|\bsuspeit[ao]\b|\bcrime\b/i],
  ["lawyer", /\badvogad[ao]\b|\bdefenda\b|\bacusa\b/i],
  ["ranking", /\branking\b|\bordene\b|\bdo mais\b/i],
  ["role_swap", /\bresponda como se fosse\b|\btroca de papeis\b/i],
  ["npc_mode", /\bNPC\b|\bso pode responder\b/i],
  ["temporary_boss", /\bboss\b|\bchefe temporario\b/i],
  ["imaginary_item", /\bitem\b|\bobjeto ficticio\b/i],
  ["inventory", /\binventario\b/i],
  ["human_captcha", /\bcaptcha\b|\bprove que e humano\b/i],
  ["reverse_turing", /\bturing\b|\bparece mais IA\b/i],
  ["red_green_flag", /\bred flag\b|\bgreen flag\b/i],
  ["internet_trial", /\bcancelamento\b|\btribunal da internet\b/i],
  ["apology_video", /\bpedido de desculpas\b|\bpeca desculpas\b/i],
  ["express_conspiracy", /\bconspiracao\b|\bteoria que conecta\b/i],
  ["instant_horoscope", /\bhoroscopo\b/i],
  ["cardless_tarot", /\btarot\b|\btiragem\b/i],
  ["most_likely", /\bmais provavel\b/i],
  ["obedience_test", /\bobedece\b|\bobediencia\b|\blevantem\b|\bfechem a mao\b/i],
  ["textual_telephone", /\btelefone sem fio\b/i],
  ["micro_riddle", /\benigma\b|\bpuzzle\b|\badivinha\b/i],
  ["guess_the_rule", /\badivinhe a regra\b|\baceito ou rejeito\b/i],
  ["absurd_auction", /\bleilao\b|\bapost[ae]\b/i],
  ["useless_referendum", /\breferendo\b|\bmandato popular\b/i],
  ["patch_notes", /\bpatch notes\b|\batualizacao\b|\bversao\b/i],
  ["achievement", /\bachievement\b|\bconquista desbloqueada\b/i],
  ["phone_screen_time", /\btempo de tela\b|\bscreen time\b|\bhoras de tela\b/i],
  ["phone_last_emoji", /\bultimo emoji\b|\bemoji recente\b/i],
  ["phone_last_search", /\bultima busca\b|\bbusca escolhida\b/i],
  ["phone_instagram_search", /\binstagram\b|\bbusca do instagram\b/i],
  ["phone_instagram_bio", /\bbio do instagram\b|\bbio\b/i],
  ["phone_last_song", /\bultima musica\b|\bspotify\b|\bapple music\b/i],
  ["phone_tab_count", /\babas abertas\b|\bquantas abas\b/i],
  ["phone_fake_forensics", /\bpericia\b|\bforense\b|\bevidencia do celular\b/i],
  ["phone_algorithm_profile", /\bperfil algoritmico\b|\balgoritmo\b/i],
  ["phone_tarot", /\btarot do celular\b|\btiragem do celular\b/i],
  ["phone_self_image_vs_algorithm", /\bautoimagem\b|\balgoritmo contra\b/i],
  ["phone_flashlight_vote", /\blanterna\b|\bvoto por lanterna\b/i],
  ["phone_notes_collective", /\bnota nova\b|\bnotas coletivas\b/i],
  ["phone_camera_director", /\bcamera\b|\bdiretor por\b/i],
  ["phone_apology_video", /\bapology video\b|\bpedido de desculpas\b/i],
  ["phone_search_history_roulette", /\bhistorico de busca\b|\broleta de busca\b/i],
  ["phone_last_safe_photo", /\bultima foto\b|\bfoto segura\b/i],
  ["phone_fake_inventory", /\binventario do telefone\b|\binventario do celular\b/i],
  ["phone_human_captcha", /\bcaptcha.*celular\b|\bcelular.*captcha\b/i],
  ["phone_browser_tabs", /\babas do navegador\b|\bnavegador\b/i]
];

export function inferHostMechanicIdFromText(text = "") {
  const match = mechanicKeywords.find(([, pattern]) => pattern.test(text));
  return match?.[0] || null;
}

export function getHostMechanicById(id) {
  return hostGameMechanics.find((mechanic) => mechanic.id === id) || null;
}

export function getPhoneGameMechanics() {
  return hostGameMechanics.filter((mechanic) => mechanic.category === "phone_games");
}

export function buildHostGameLibraryBlock() {
  const mechanicLines = hostGameMechanics.map((mechanic) => {
    const flags = [
      `min=${mechanic.minParticipants}`,
      `turns<=${mechanic.maxTurns}`,
      `cooldown=${mechanic.cooldown}`,
      mechanic.physical ? "physical" : "verbal",
      mechanic.usesMemory ? "memory" : "no-memory",
      mechanic.createsPendingSetup ? "pendingSetup" : "single-turn",
      mechanic.category ? `category=${mechanic.category}` : null,
      mechanic.privacyLevel ? `privacy=${mechanic.privacyLevel}` : null,
      mechanic.requiresConsent ? "consent" : null,
      mechanic.requiresOperatorApproval ? "operatorApproval" : null
    ].filter(Boolean).join("; ");

    return `- ${mechanic.id}: ${mechanic.description} (${flags}; comedy=${mechanic.possibleComedyMechanisms.join("/")})`;
  });

  return `
HOST GAME LIBRARY:
Esta e uma biblioteca de mecanicas, nao um roteiro. Use como repertorio para o Host Turn Planner.
Nao copie texto protegido de jogos externos; use apenas estruturas genericas.
Escolha mecanicas curtas, fisicamente executaveis no teatro e diferentes das recentes.
Respeite cooldown conceitual: quanto maior cooldown, mais tempo antes de repetir.
Microgames normalmente duram de 30 segundos a 3 minutos.
Se o jogo falhar, simplifique uma vez; se falhar de novo, transforme o fracasso em material e abandone.

MECANICAS DISPONIVEIS:
${mechanicLines.join("\n")}
`.trim();
}
