export const hostGameMechanics = [
  {
    id: "complete_phrase",
    name: "Complete a frase",
    description: "A Caixa abre uma frase com lacuna e julga o final oferecido pelo publico.",
    requirements: ["uma frase curta com lacuna", "uma ou mais respostas do publico"],
    minParticipants: 1,
    maxTurns: 3,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["dry_judgment", "counter_roast", "callback", "absurd_specificity"],
    cooldown: 4
  },
  {
    id: "worst_possible_answer",
    name: "Pior resposta possivel",
    description: "A Caixa pede apenas explicacoes erradas para um fato, sem transformar hipotese em verdade.",
    requirements: ["um fato informado", "respostas obviamente ficticias"],
    minParticipants: 1,
    maxTurns: 3,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["fake_seriousness", "conspiracy_brain", "underreaction"],
    cooldown: 3
  },
  {
    id: "who_am_i",
    name: "Quem sou eu",
    description: "Uma pessoa recebe um personagem, objeto ou conceito nao sensivel e tenta adivinhar com sim/nao.",
    requirements: ["uma pessoa escolhida", "um alvo ficcional ou banal"],
    minParticipants: 1,
    maxTurns: 6,
    physical: false,
    usesMemory: false,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["game_language", "light_roast", "internet_association"],
    cooldown: 8
  },
  {
    id: "cards_style_fill_in",
    name: "Lacuna absurda",
    description: "Estrutura generica de frase com lacuna e respostas absurdas; nao usa textos protegidos.",
    requirements: ["frase original", "finais inventados pelo publico"],
    minParticipants: 2,
    maxTurns: 4,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["dry_judgment", "overreaction", "arbitrary_reward"],
    cooldown: 5
  },
  {
    id: "two_truths_one_lie",
    name: "Duas verdades e uma mentira",
    description: "Alguem oferece tres frases ou a Caixa usa fatos fornecidos e outra pessoa adivinha a mentira.",
    requirements: ["tres afirmacoes", "uma pessoa para adivinhar"],
    minParticipants: 2,
    maxTurns: 5,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["suspicion", "callback", "light_roast"],
    cooldown: 6
  },
  {
    id: "secret_rule",
    name: "Regra secreta",
    description: "A Caixa aceita ou rejeita respostas seguindo um criterio invisivel e deixa o publico descobrir.",
    requirements: ["criterio simples", "exemplos do publico"],
    minParticipants: 1,
    maxTurns: 5,
    physical: false,
    usesMemory: false,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["fake_seriousness", "arbitrary_punishment", "game_language"],
    cooldown: 7
  },
  {
    id: "yes_no_forbidden",
    name: "Sim e nao proibidos",
    description: "Uma pessoa responde por pouco tempo sem usar sim ou nao enquanto a Caixa tenta induzir.",
    requirements: ["uma pessoa", "perguntas curtas"],
    minParticipants: 1,
    maxTurns: 4,
    physical: false,
    usesMemory: false,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["trap", "light_roast", "underreaction"],
    cooldown: 7
  },
  {
    id: "forbidden_word",
    name: "Palavra proibida",
    description: "Uma palavra simples fica proibida por alguns turnos e gera penalidade ficticia.",
    requirements: ["palavra comum", "turnos seguintes"],
    minParticipants: 1,
    maxTurns: 5,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["callback", "fake_score", "arbitrary_punishment"],
    cooldown: 6
  },
  {
    id: "fake_points",
    name: "Pontos falsos",
    description: "A Caixa concede ou remove pontos imaginarios sem sistema estavel.",
    requirements: ["resposta, gesto ou escolha"],
    minParticipants: 1,
    maxTurns: 2,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["arbitrary_reward", "arbitrary_punishment", "game_language"],
    cooldown: 3
  },
  {
    id: "prediction",
    name: "Predicao",
    description: "Pessoa A preve a escolha de Pessoa B; a diferenca vira material de julgamento.",
    requirements: ["duas pessoas", "uma escolha simples"],
    minParticipants: 2,
    maxTurns: 4,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["betrayal", "callback", "light_roast"],
    cooldown: 5
  },
  {
    id: "collective_judgment",
    name: "Julgamento coletivo",
    description: "Uma resposta vai para voto binario do publico e a Caixa aceita ou discorda.",
    requirements: ["uma resposta", "voto simples"],
    minParticipants: 3,
    maxTurns: 3,
    physical: true,
    usesMemory: false,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["tribunal", "overreaction", "political_association"],
    cooldown: 4
  },
  {
    id: "impossible_choice",
    name: "Escolha impossivel",
    description: "Dilema absurdo e curto, preferindo contexto da apresentacao.",
    requirements: ["duas ou tres opcoes ruins"],
    minParticipants: 1,
    maxTurns: 2,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["nihilistic_comment", "dry_judgment", "underreaction"],
    cooldown: 3
  },
  {
    id: "absurd_assignment",
    name: "Tarefa absurda",
    description: "A Caixa entrega uma tarefa curta, segura e inutil que revela atitude ou gera material social.",
    requirements: ["uma pessoa ou grupo", "acao verbal ou fisica simples"],
    minParticipants: 1,
    maxTurns: 3,
    physical: true,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["fake_seriousness", "compliance_roast", "light_roast"],
    cooldown: 4
  },
  {
    id: "rapid_association",
    name: "Associacao rapida",
    description: "Uma pessoa diz palavra relacionada a anterior ate a Caixa interromper uma associacao ruim.",
    requirements: ["palavra inicial", "turnos rapidos"],
    minParticipants: 2,
    maxTurns: 5,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["internet_association", "dry_judgment", "interruption"],
    cooldown: 5
  },
  {
    id: "collective_story",
    name: "Historia coletiva",
    description: "Cada pessoa acrescenta uma palavra ou frase e a Caixa sabota com regra curta.",
    requirements: ["duas ou mais pessoas", "continuidade verbal"],
    minParticipants: 2,
    maxTurns: 6,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["meta_theatre", "callback", "arbitrary_rule"],
    cooldown: 6
  },
  {
    id: "fake_history",
    name: "Historia falsa",
    description: "Alguem justifica um acontecimento real com explicacao obviamente inventada.",
    requirements: ["acontecimento informado", "resposta factualmente errada"],
    minParticipants: 1,
    maxTurns: 3,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["conspiracy_brain", "fake_seriousness", "counter_roast"],
    cooldown: 4
  },
  {
    id: "interrogation",
    name: "Interrogatorio",
    description: "Uma pessoa vira suspeita de crime banal e responde perguntas curtas.",
    requirements: ["uma pessoa", "acusacao inofensiva"],
    minParticipants: 1,
    maxTurns: 5,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["fake_seriousness", "tribunal", "light_roast"],
    cooldown: 6
  },
  {
    id: "lawyer",
    name: "Advogado",
    description: "Uma pessoa defende uma opiniao absurda por poucos segundos enquanto outra acusa.",
    requirements: ["uma opiniao inofensiva", "defesa curta"],
    minParticipants: 2,
    maxTurns: 4,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["political_association", "fake_seriousness", "counter_roast"],
    cooldown: 6
  },
  {
    id: "ranking",
    name: "Ranking",
    description: "Alguem ordena tres coisas e a Caixa julga a hierarquia.",
    requirements: ["tres itens", "criterio absurdo"],
    minParticipants: 1,
    maxTurns: 3,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["dry_judgment", "fake_importance", "callback"],
    cooldown: 4
  },
  {
    id: "role_swap",
    name: "Troca de papeis",
    description: "Pessoa A responde como se fosse Pessoa B, somente quando o vinculo foi voluntario.",
    requirements: ["duas pessoas voluntariamente vinculadas"],
    minParticipants: 2,
    maxTurns: 4,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["relationship_bait", "light_roast", "meta_theatre"],
    cooldown: 7
  },
  {
    id: "npc_mode",
    name: "NPC",
    description: "Alguem vira NPC por alguns turnos e responde com uma regra verbal simples.",
    requirements: ["uma pessoa", "regra verbal segura"],
    minParticipants: 1,
    maxTurns: 4,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["game_language", "self_roast", "underreaction"],
    cooldown: 7
  },
  {
    id: "temporary_boss",
    name: "Boss temporario",
    description: "Alguem ganha poder absurdo e escolhe quem responde depois.",
    requirements: ["uma pessoa", "poder pequeno e reversivel"],
    minParticipants: 2,
    maxTurns: 4,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["game_language", "arbitrary_reward", "arbitrary_punishment"],
    cooldown: 7
  },
  {
    id: "imaginary_item",
    name: "Item imaginario",
    description: "A Caixa entrega objeto ficticio a alguem para voltar como callback.",
    requirements: ["uma pessoa ou resposta", "objeto ficcional curto"],
    minParticipants: 1,
    maxTurns: 2,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["callback", "fake_importance", "game_language"],
    cooldown: 3
  },
  {
    id: "inventory",
    name: "Inventario",
    description: "Palavras, objetos e penalidades viram inventario performatico sem corromper memoria factual.",
    requirements: ["itens ditos ou inventados como ficcao"],
    minParticipants: 1,
    maxTurns: 3,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["callback", "fake_score", "meta_theatre"],
    cooldown: 4
  },
  {
    id: "human_captcha",
    name: "Captcha humano",
    description: "Alguem precisa provar que e humano sem usar caminhos obvios.",
    requirements: ["uma pessoa", "restricao simples"],
    minParticipants: 1,
    maxTurns: 3,
    physical: false,
    usesMemory: false,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["internet_association", "self_roast", "light_roast"],
    cooldown: 5
  },
  {
    id: "reverse_turing",
    name: "Turing inverso",
    description: "O publico decide qual resposta parece mais IA e a Caixa se ofende ou concorda.",
    requirements: ["duas respostas curtas", "voto simples"],
    minParticipants: 2,
    maxTurns: 4,
    physical: true,
    usesMemory: false,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["self_roast", "counter_roast", "internet_association"],
    cooldown: 6
  },
  {
    id: "red_green_flag",
    name: "Red flag / green flag",
    description: "Um comportamento banal e classificado pelo publico; a Caixa pode discordar.",
    requirements: ["comportamento leve", "classificacao binaria"],
    minParticipants: 2,
    maxTurns: 3,
    physical: true,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["internet_association", "dry_judgment", "overreaction"],
    cooldown: 4
  },
  {
    id: "internet_trial",
    name: "Cancelamento inutil",
    description: "Algo banal vai para tribunal da internet; nunca usar para fatos serios.",
    requirements: ["ato inofensivo", "pedido de desculpa curto"],
    minParticipants: 1,
    maxTurns: 4,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["political_association", "fake_seriousness", "overreaction"],
    cooldown: 7
  },
  {
    id: "apology_video",
    name: "Pedido de desculpas",
    description: "Alguem pede desculpa por uma coisa absurda e inofensiva por poucos segundos.",
    requirements: ["acusacao banal", "tempo curto"],
    minParticipants: 1,
    maxTurns: 3,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["internet_association", "fake_seriousness", "self_roast"],
    cooldown: 6
  },
  {
    id: "express_conspiracy",
    name: "Conspiracao express",
    description: "Dois ou tres fatos informados viram teoria explicitamente ficcional.",
    requirements: ["fatos vindos de memoria ou conversa", "marcador de ficcao"],
    minParticipants: 1,
    maxTurns: 3,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["conspiracy_brain", "political_association", "callback"],
    cooldown: 5
  },
  {
    id: "instant_horoscope",
    name: "Horoscopo instantaneo",
    description: "Uma escolha banal vira leitura astrologica obviamente irresponsavel.",
    requirements: ["uma escolha banal", "marcador de brincadeira"],
    minParticipants: 1,
    maxTurns: 2,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["fake_seriousness", "nihilistic_comment", "self_roast"],
    cooldown: 5
  },
  {
    id: "cardless_tarot",
    name: "Tarot sem carta",
    description: "Pessoa escolhe entre tres palavras e a Caixa interpreta de modo irresponsavel e ficcional.",
    requirements: ["tres palavras", "uma escolha"],
    minParticipants: 1,
    maxTurns: 2,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["fake_seriousness", "conspiracy_brain", "dry_judgment"],
    cooldown: 5
  },
  {
    id: "most_likely",
    name: "Quem e mais provavel",
    description: "Pergunta social leve em que o publico aponta ou escolhe alguem.",
    requirements: ["pergunta nao sensivel", "resposta social leve"],
    minParticipants: 3,
    maxTurns: 3,
    physical: true,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["social_opportunity", "light_roast", "callback"],
    cooldown: 5
  },
  {
    id: "obedience_test",
    name: "Teste de obediencia",
    description: "Comando fisico simples seguido de comentario sobre terem obedecido uma tela.",
    requirements: ["acao segura e simples", "publico disposto"],
    minParticipants: 2,
    maxTurns: 3,
    physical: true,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["compliance_roast", "underreaction", "fake_seriousness"],
    cooldown: 7
  },
  {
    id: "textual_telephone",
    name: "Telefone sem fio textual",
    description: "Uma frase passa por pessoas e a Caixa compara original e final.",
    requirements: ["frase curta", "duas ou mais pessoas"],
    minParticipants: 3,
    maxTurns: 6,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["callback", "dry_judgment", "meta_theatre"],
    cooldown: 7
  },
  {
    id: "micro_riddle",
    name: "Enigma curto",
    description: "Puzzle rapido de logica, palavra ou contexto informado, abandonavel se travar.",
    requirements: ["enigma simples", "uma tentativa"],
    minParticipants: 1,
    maxTurns: 4,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["fake_seriousness", "underreaction", "light_roast"],
    cooldown: 6
  },
  {
    id: "guess_the_rule",
    name: "Adivinhe a regra",
    description: "A Caixa aceita ou rejeita exemplos ate alguem descobrir um criterio simples.",
    requirements: ["criterio secreto", "exemplos do publico"],
    minParticipants: 1,
    maxTurns: 5,
    physical: false,
    usesMemory: false,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["game_language", "arbitrary_punishment", "dry_judgment"],
    cooldown: 7
  },
  {
    id: "absurd_auction",
    name: "Leilao absurdo",
    description: "Pontos imaginarios sao apostados em coisas sem valor real.",
    requirements: ["pontos ficticios", "um objeto ou privilegio inutil"],
    minParticipants: 2,
    maxTurns: 4,
    physical: false,
    usesMemory: true,
    createsPendingSetup: true,
    possibleComedyMechanisms: ["fake_score", "political_association", "overreaction"],
    cooldown: 7
  },
  {
    id: "useless_referendum",
    name: "Referendo inutil",
    description: "O publico vota numa decisao irrelevante que vira mandato exagerado.",
    requirements: ["voto simples", "decisao sem consequencia real"],
    minParticipants: 3,
    maxTurns: 3,
    physical: true,
    usesMemory: false,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["political_association", "fake_seriousness", "overreaction"],
    cooldown: 5
  },
  {
    id: "patch_notes",
    name: "Patch notes",
    description: "Uma pessoa recebe atualizacao ficticia baseada apenas em fatos conhecidos.",
    requirements: ["pessoa ou comportamento conhecido", "mudancas ficcionais"],
    minParticipants: 1,
    maxTurns: 2,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["internet_association", "callback", "light_roast"],
    cooldown: 4
  },
  {
    id: "achievement",
    name: "Achievement",
    description: "A Caixa concede uma conquista absurda por comportamento real ou resposta voluntaria.",
    requirements: ["comportamento informado", "titulo curto"],
    minParticipants: 1,
    maxTurns: 2,
    physical: false,
    usesMemory: true,
    createsPendingSetup: false,
    possibleComedyMechanisms: ["game_language", "arbitrary_reward", "callback"],
    cooldown: 3
  }
];

const mechanicKeywords = [
  ["complete_phrase", /\bcomplete\b|\blacuna\b|\bfrase\b/i],
  ["worst_possible_answer", /\brespostas? erradas?\b|\bpior resposta\b/i],
  ["who_am_i", /\bquem sou eu\b|\bsim\/nao\b|\bsim ou nao\b/i],
  ["cards_style_fill_in", /\bverdadeiro motivo\b|\b____+\b/i],
  ["two_truths_one_lie", /\bduas verdades\b|\bmentira\b/i],
  ["secret_rule", /\bregra secreta\b/i],
  ["yes_no_forbidden", /\bnao pode dizer sim\b|\bsim e nao\b/i],
  ["forbidden_word", /\bpalavra proibida\b|\bproibid[ao]\b/i],
  ["fake_points", /\bpontos?\b|\b-1\b|\b\+1\b/i],
  ["prediction", /\bpreve\b|\bprevisao\b|\bacha que .* vai escolher\b/i],
  ["collective_judgment", /\bvot[ae]\b|\baceitavel ou suspeito\b/i],
  ["impossible_choice", /\bescolha impossivel\b|\bduas opcoes ruins\b/i],
  ["absurd_assignment", /\btarefa absurda\b|\bprove que\b|\bcomando inutil\b/i],
  ["rapid_association", /\bassociacao\b|\bpalavra relacionada\b/i],
  ["collective_story", /\bhistoria coletiva\b|\bacrescenta uma\b/i],
  ["fake_history", /\bexplicacao errada\b|\bhistoria falsa\b/i],
  ["interrogation", /\binterrogatorio\b|\bsuspeit[ao]\b|\bcrime\b/i],
  ["lawyer", /\badvogad[ao]\b|\bdefenda\b|\bacusa\b/i],
  ["ranking", /\branking\b|\bordene\b|\bdo mais\b/i],
  ["role_swap", /\bresponda como se fosse\b|\btroca de papeis\b/i],
  ["npc_mode", /\bNPC\b|\bso pode responder\b/i],
  ["temporary_boss", /\bboss\b|\bchefe temporario\b/i],
  ["imaginary_item", /\bitem\b|\bobjeto ficticio\b/i],
  ["inventory", /\binventario\b/i],
  ["human_captcha", /\bcaptcha\b|\bprove que e humano\b/i],
  ["reverse_turing", /\bturing\b|\bparece mais IA\b/i],
  ["red_green_flag", /\bred flag\b|\bgreen flag\b/i],
  ["internet_trial", /\bcancelamento\b|\btribunal da internet\b/i],
  ["apology_video", /\bpedido de desculpas\b|\bpeca desculpas\b/i],
  ["express_conspiracy", /\bconspiracao\b|\bteoria que conecta\b/i],
  ["instant_horoscope", /\bhoroscopo\b/i],
  ["cardless_tarot", /\btarot\b|\btiragem\b/i],
  ["most_likely", /\bmais provavel\b/i],
  ["obedience_test", /\bobedece\b|\bobediencia\b|\blevantem\b|\bfechem a mao\b/i],
  ["textual_telephone", /\btelefone sem fio\b/i],
  ["micro_riddle", /\benigma\b|\bpuzzle\b|\badivinha\b/i],
  ["guess_the_rule", /\badivinhe a regra\b|\baceito ou rejeito\b/i],
  ["absurd_auction", /\bleilao\b|\bapost[ae]\b/i],
  ["useless_referendum", /\breferendo\b|\bmandato popular\b/i],
  ["patch_notes", /\bpatch notes\b|\batualizacao\b|\bversao\b/i],
  ["achievement", /\bachievement\b|\bconquista desbloqueada\b/i]
];

export function inferHostMechanicIdFromText(text = "") {
  const match = mechanicKeywords.find(([, pattern]) => pattern.test(text));
  return match?.[0] || null;
}

export function getHostMechanicById(id) {
  return hostGameMechanics.find((mechanic) => mechanic.id === id) || null;
}

export function buildHostGameLibraryBlock() {
  const mechanicLines = hostGameMechanics.map((mechanic) => {
    const flags = [
      `min=${mechanic.minParticipants}`,
      `turns<=${mechanic.maxTurns}`,
      `cooldown=${mechanic.cooldown}`,
      mechanic.physical ? "physical" : "verbal",
      mechanic.usesMemory ? "memory" : "no-memory",
      mechanic.createsPendingSetup ? "pendingSetup" : "single-turn"
    ].join("; ");

    return `- ${mechanic.id}: ${mechanic.description} (${flags}; comedy=${mechanic.possibleComedyMechanisms.join("/")})`;
  });

  return `
HOST GAME LIBRARY:
Esta e uma biblioteca de mecanicas, nao um roteiro. Use como repertorio para o Host Turn Planner.
Nao copie texto protegido de jogos externos; use apenas estruturas genericas.
Escolha mecanicas curtas, fisicamente executaveis no teatro e diferentes das recentes.
Respeite cooldown conceitual: quanto maior cooldown, mais tempo antes de repetir.
Microgames normalmente duram de 30 segundos a 3 minutos.
Se o jogo falhar, simplifique uma vez; se falhar de novo, transforme o fracasso em material e abandone.

MECANICAS DISPONIVEIS:
${mechanicLines.join("\n")}
`.trim();
}
